# Generated by Django 4.2.23 on 2025-06-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('alternativa_a', models.CharField(max_length=200)),
                ('alternativa_b', models.CharField(max_length=200)),
                ('alternativa_c', models.CharField(max_length=200)),
                ('alternativa_d', models.CharField(max_length=200)),
                ('alternativa_correta', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('explicacao', models.TextField()),
                ('dica', models.TextField(default='Pense bem sobre o conceito de educação financeira envolvido.')),
            ],
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=1)),
                ('lives', models.IntegerField(default=3)),
                ('current_question', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, to='game.question')),
            ],
        ),
    ]
