# Generated by Django 4.2.23 on 2025-06-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='answered_questions',
            field=models.ManyToManyField(blank=True, related_name='games_answered', to='game.question'),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
