# Generated by Django 4.2.23 on 2025-06-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gamestate_answered_questions_gamestate_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='board_position',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
