# Generated by Django 4.2.23 on 2025-06-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_question_board_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['stage']},
        ),
        migrations.RemoveField(
            model_name='question',
            name='board_position',
        ),
        migrations.AddField(
            model_name='question',
            name='stage',
            field=models.IntegerField(default=1),
        ),
    ]
